

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/resizeable.css";
import { ToggleContextProvider } from "@/contexts/toggleSide";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 


  return (
    <html lang="en" suppressHydrationWarning>
      <body
<<<<<<< HEAD
        className={`${geistSans.variable}
        ${geistMono.variable} antialiased`}

        suppressHydrationWarning={true}
=======
        
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         suppressHydrationWarning={true}
>>>>>>> 52216e4d9ea092d4ee9985da172331fce1debb2b
      >
      
          <ToggleContextProvider>
           
          
            {children}
        
          
          </ToggleContextProvider>
        
      </body>
    </html>
  );
}
