import {
  LayoutPanelTop,
  Grid3x2,
  Text,
  Image,
  Heading,
  MousePointerClick,
  ChevronDown,
  ChevronUp,
  PanelLeft,
  Settings,
  Laptop,
  Tablet,
  Smartphone,
  AlignLeft,
  AlignRight,
  AlignCenter,
  AlignJustify,
  Link2,
  Unlink2,
  Link2Off,
  AlignVerticalJustifyStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalSpaceAround,
  AlignVerticalSpaceBetween,
  Trash2,
  Copy,
  Upload,
  Video,
  Play,
  TriangleAlert,
  ImagePlus,
  Plus,
  MoveLeft,
  MoveRight,
  MoveUp,
  MoveDown,
  AlignHorizontalJustifyStart,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyCenter,
  AlignHorizontalSpaceAround,
  AlignHorizontalSpaceBetween,
  ArrowRightFromLine,
  ArrowLeftToLine,
  Pencil,
  ScanEye,
  ImageOff,
  Rabbit,
  MousePointer,
  Move,
  TextCursor,
  Cross,
  UnfoldHorizontal,
  Hand,
  MoveHorizontal,
  MoveVertical,
  MoveDiagonal,
  MoveDiagonal2,
  Ban,
  Pointer,
  LoaderCircle,
  ZoomIn,
  ZoomOut,
  PanelRight,
  PanelTop,
  PanelBottom,
  Eye,
  Save,
  PanelBottomOpen,
  PanelBottomClose,
  Star,
  List,
  Logs,
  Menu,
  Search,
  Facebook,
  Twitter,
  Linkedin,
  Instagram
  


} from 'lucide-react';


import { FaTabletAlt } from "react-icons/fa";
import { MdAlignVerticalBottom, MdAlignVerticalCenter, MdAlignVerticalTop } from 'react-icons/md';
import { TbDiabolo } from 'react-icons/tb';
import { TbNavigationQuestion } from "react-icons/tb";
import { BsQuestion } from "react-icons/bs";
import { ImInsertTemplate } from 'react-icons/im';


export const iconMap : {[key:string]: React.ElementType} ={
  panelTop : LayoutPanelTop,
  grid : Grid3x2,
  text: Text,
  image: Image,
  heading: Heading,
  mouseClick: MousePointerClick,
  downarrow : ChevronDown,
  uparrow : ChevronUp,
  panelLeft: PanelLeft,
  panelRight : PanelRight,
  paneltop: PanelTop,
  panelbottom:PanelBottom, 
  settings : Settings,
  laptop: Laptop,
  tablet: Tablet,
  smartphone : Smartphone,
  left : AlignLeft,
  center: AlignCenter,
  right: AlignRight,
  justify: AlignJustify,
  alllink : Link2,
  halflink: Unlink2,
  unlink : Link2Off,
  vStart : AlignVerticalJustifyStart,
  vCenter: AlignVerticalJustifyCenter,
  vEnd: AlignVerticalJustifyEnd,
  vSpaceAround:  AlignVerticalSpaceAround,
  vSpaceBetween: AlignVerticalSpaceBetween,
  trash: Trash2,
  copy: Copy,
  upload: Upload,
  video: Video,
  play : Play,
  error: TriangleAlert,
  addimg: ImagePlus,
  delete: Trash2,
  plus: Plus,
  ldirection: MoveLeft,
  rdirection: MoveRight,
  tdirection:MoveUp,
  ddirection: MoveDown,
  jstart: AlignHorizontalJustifyStart,
  jend: AlignHorizontalJustifyEnd,
  jcenter: AlignHorizontalJustifyCenter,
  jspacearound :  AlignHorizontalSpaceAround,
  jspacebetween: AlignHorizontalSpaceBetween,
  rVStart : MdAlignVerticalTop, 
  rVCenter : MdAlignVerticalCenter,
  rVEnd: MdAlignVerticalBottom,
  pLeft : ArrowRightFromLine,
  pRight : ArrowLeftToLine,
  pencil : Pencil,
  scanEye : ScanEye,
  hLeft : ArrowRightFromLine,
  hRight : ArrowLeftToLine,
  moMedia : ImageOff ,
  rabbit : Rabbit,
  mousePointer: MousePointer,
  navigationQuestion:  TbNavigationQuestion,
  move : Move,
  textCursor : TextCursor,
  cross : Cross,
  colresize : UnfoldHorizontal,
  
  hand:Hand,
  moveHorizontal:MoveHorizontal,
  help:BsQuestion,
  moveVertical : MoveVertical,
  moveDiagonal :  MoveDiagonal,
  nwresize : MoveDiagonal2,
  ban : Ban,
  point:Pointer,
  loader:LoaderCircle,
  MoveDiag:MoveDiagonal2,
  zoomin : ZoomIn,
  zoomout : ZoomOut,
  eye:Eye,  
  save:Save,
  panelbottomOpen: PanelBottomOpen,
  panelbottomClose: PanelBottomClose,
  star: Star,
  template: ImInsertTemplate,
  list : List,
  logs : Logs,
  menu : Menu,
  search:Search,
  facebook:Facebook,
  twitter:Twitter,
  linkedin:Linkedin,
  insta:Instagram 




}


